# Generated by Django 4.2 on 2024-04-22 14:11

from django.db import migrations, models
import django.db.models.deletion
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_category_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='favourite',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='CategoryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.ImageField(max_length=500, upload_to=products.models.category_image_directory_path)),
                ('category', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image', to='products.category')),
            ],
            options={
                'verbose_name': 'Category image',
                'verbose_name_plural': 'Category images',
                'ordering': ['pk'],
            },
        ),
    ]
