# Generated by Django 4.2 on 2024-04-22 15:41

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_category_favourite_categoryimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='product',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['pk', 'title'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=products.models.category_image_directory_path),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=products.models.product_images_directory_path),
        ),
        migrations.DeleteModel(
            name='CategoryImage',
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
