# Generated by Django 4.2 on 2024-04-22 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_productspecification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='images',
        ),
    ]
