# Generated by Django 4.2 on 2024-04-22 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_rename_image_product_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='dateFrom',
            field=models.DateField(default=''),
        ),
        migrations.AlterField(
            model_name='sale',
            name='dateTo',
            field=models.DateField(blank=True),
        ),
    ]
