# Generated by Django 4.2 on 2024-04-23 13:52

from django.db import migrations, models
import django.db.models.deletion
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_product_images_productimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
        migrations.CreateModel(
            name='CategoryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.CharField(blank=True, max_length=100)),
                ('image', models.FileField(upload_to=products.models.category_image_directory_path)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.category', verbose_name='category')),
            ],
            options={
                'verbose_name': 'Category image',
                'verbose_name_plural': 'Category images',
                'ordering': ['pk'],
            },
        ),
    ]
