# Generated by Django 4.2 on 2024-04-23 13:59

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_categoryimage_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoryimage',
            name='image',
        ),
        migrations.AlterField(
            model_name='categoryimage',
            name='src',
            field=models.ImageField(upload_to=products.models.category_image_directory_path),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to=products.models.product_images_directory_path),
        ),
    ]
