# Generated by Django 4.2 on 2024-04-23 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_remove_categoryimage_image_alter_categoryimage_src_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryimage',
            name='category',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image', to='products.category'),
        ),
    ]
